// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  tabsContract,
  tabsOrientations,
  tabsSizes,
  tabsSlots,
  tabsStates,
  tabsVariants,
  tabsVisualArchetypes,
} from './tabs-contract'
export type {
  TabsContract,
  TabsOrientation,
  TabsSize,
  TabsSlot,
  TabsState,
  TabsVariant,
  TabsVisualArchetype,
} from './tabs-contract'
