// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  inputOTPContract,
  inputOTPSlots,
  inputOTPStates,
  inputOTPVisualArchetypes,
} from './input-otp-contract'
export type {
  InputOTPContract,
  InputOTPSlot,
  InputOTPState,
  InputOTPVisualArchetype,
} from './input-otp-contract'
