import { ChevronDown } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import changelog, {
  type ChangelogPackageChange,
  type ReleasedChangelogSection,
} from 'virtual:atom63-changelog'

const bumpLabel = {
  major: 'Major',
  minor: 'Minor',
  patch: 'Patch',
} as const

function ChangeMarkdown({ children }: { children: string }) {
  return (
    <ReactMarkdown
      components={{
        a: ({ children: linkChildren, href }) => (
          <a href={href} rel="noopener noreferrer" target="_blank">
            {linkChildren}
          </a>
        ),
        code: ({ children: codeChildren }) => <code>{codeChildren}</code>,
      }}
      remarkPlugins={[remarkGfm]}
    >
      {children}
    </ReactMarkdown>
  )
}

function PackageChanges({ changes }: { changes: ChangelogPackageChange[] }) {
  return (
    <ul aria-label="Affected packages" className="changelog-package-list">
      {changes.map(change => (
        <li className="changelog-package" key={change.name}>
          <code>{change.name}</code>
          <span aria-hidden>·</span>
          <span>{bumpLabel[change.bump]}</span>
        </li>
      ))}
    </ul>
  )
}

function ReleasedSection({ section }: { section: ReleasedChangelogSection }) {
  return (
    <section className="changelog-release-section">
      <h4>{section.label}</h4>
      <div className="changelog-markdown">
        <ChangeMarkdown>{section.body}</ChangeMarkdown>
      </div>
    </section>
  )
}

export function ChangelogTimeline() {
  const releasedCount = changelog.releasedPackages.reduce(
    (count, packageChangelog) => count + packageChangelog.releases.length,
    0
  )

  return (
    <div className="changelog-timeline">
      <section aria-labelledby="unreleased-changes" className="changelog-group">
        <header className="changelog-group-header">
          <div className="changelog-group-title">
            <h2 id="unreleased-changes">Unreleased</h2>
            <span>
              {changelog.pending.length}{' '}
              {changelog.pending.length === 1 ? 'changeset' : 'changesets'}
            </span>
          </div>
          <p>
            Version numbers are assigned when Changesets updates package manifests. Entries here are
            release intent, not a fabricated release date.
          </p>
        </header>

        {changelog.pending.length > 0 ? (
          <div className="changelog-entry-list">
            {changelog.pending.map(entry => (
              <article className="changelog-entry" key={entry.id}>
                <PackageChanges changes={entry.packages} />
                <div className="changelog-markdown">
                  <ChangeMarkdown>{entry.body}</ChangeMarkdown>
                </div>
              </article>
            ))}
          </div>
        ) : (
          <p className="changelog-empty">No pending changesets.</p>
        )}
      </section>

      <section aria-labelledby="released-changes" className="changelog-group">
        <header className="changelog-group-header">
          <div className="changelog-group-title">
            <h2 id="released-changes">Released</h2>
            <span>
              {releasedCount} {releasedCount === 1 ? 'version' : 'versions'} across{' '}
              {changelog.releasedPackages.length}{' '}
              {changelog.releasedPackages.length === 1 ? 'package' : 'packages'}
            </span>
          </div>
          <p>
            Released entries come directly from package changelogs generated by the release
            workflow, including pull request and commit attribution.
          </p>
        </header>

        <div className="changelog-release-list">
          {changelog.releasedPackages.map(packageChangelog => (
            <section
              className="changelog-release-package"
              data-toc-exclude=""
              key={packageChangelog.name}
            >
              <header>
                <div>
                  <h3>
                    <code>{packageChangelog.name}</code>
                  </h3>
                  {packageChangelog.description ? <p>{packageChangelog.description}</p> : null}
                </div>
              </header>

              <div>
                {packageChangelog.releases.map((release, index) => (
                  <details
                    className="changelog-release-disclosure"
                    key={release.version}
                    open={index === 0}
                  >
                    <summary>
                      <span>{release.version}</span>
                      <span>{release.sections.map(section => section.label).join(' · ')}</span>
                      <ChevronDown aria-hidden />
                    </summary>
                    <div className="changelog-release-body">
                      {release.sections.map(section => (
                        <ReleasedSection key={section.label} section={section} />
                      ))}
                    </div>
                  </details>
                ))}
              </div>
            </section>
          ))}
        </div>
      </section>
    </div>
  )
}
