// Generated by scripts/generate-component-contracts.mjs from packages/ui-foundation/contracts/components/checkbox.json.
// Do not edit; change the JSON and run `pnpm --filter @atom63/ui-foundation generate:contracts`.

import type { A11yPatternBinding } from '../../a11y/types'
import type { VisualArchetypeId } from '../../visual-archetypes'

export const checkboxSizes = ['sm', 'md'] as const
export const checkboxStates = [
  'unchecked',
  'checked',
  'indeterminate',
  'disabled',
  'invalid',
] as const
export const checkboxSlots = ['checkbox', 'checkbox-indicator'] as const
export const checkboxVisualArchetypes = ['choice'] as const satisfies readonly VisualArchetypeId[]

export type CheckboxSize = (typeof checkboxSizes)[number]
export type CheckboxState = (typeof checkboxStates)[number]
export type CheckboxSlot = (typeof checkboxSlots)[number]
export type CheckboxVisualArchetype = (typeof checkboxVisualArchetypes)[number]

export interface CheckboxContract {
  /** The WAI-ARIA APG pattern the component implements. */
  accessibility: A11yPatternBinding
  defaultSize: CheckboxSize
  sizes: readonly CheckboxSize[]
  states: readonly CheckboxState[]
  slots: readonly CheckboxSlot[]
  visualArchetypes: readonly CheckboxVisualArchetype[]
}

export const checkboxContract = {
  accessibility: { pattern: 'checkbox' },
  defaultSize: 'md',
  sizes: checkboxSizes,
  states: checkboxStates,
  slots: checkboxSlots,
  visualArchetypes: checkboxVisualArchetypes,
} satisfies CheckboxContract
