import type { A11yPatternContract } from './types'

const TRIGGER_EXPANDED = {
  target: { part: 'trigger' },
  attribute: 'aria-expanded',
  equals: 'true',
} as const
const TRIGGER_COLLAPSED = { ...TRIGGER_EXPANDED, equals: 'false' } as const

/**
 * Menu Button: a button that opens a menu. The keys inside the open menu come
 * from the Menu and Menubar pattern, which the menu button page defers to.
 *
 * Option `wrap`: the APG lets Down Arrow and Up Arrow either wrap from the last
 * item to the first (`wrap`) or stop at the ends (`stop`).
 */
export const menuButtonPattern: A11yPatternContract = {
  id: 'menu-button',
  name: 'Menu Button',
  source: 'https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/',
  options: { wrap: ['wrap', 'stop'] },
  parts: {
    trigger: {
      description: 'The button that opens the menu.',
      name: 'required',
      role: 'button',
    },
    menu: {
      description: 'The menu, labelled by the button that controls it or by aria-label.',
      name: 'required',
      role: 'menu',
      whileOpen: true,
    },
    item: {
      description: 'The items of the menu.',
      multiple: true,
      name: 'required',
      role: 'menuitem',
      whileOpen: true,
      within: 'menu',
    },
  },
  popup: 'menu',
  opener: { part: 'trigger', keys: '{Enter}' },
  tree: [{ part: 'menu', children: [{ part: 'item' }] }],
  structure: [
    {
      id: 'trigger-has-popup',
      requirement: 'required',
      rule: 'The button has aria-haspopup set to menu or true.',
      target: { part: 'trigger' },
      attribute: 'aria-haspopup',
      equals: ['menu', 'true'],
    },
    {
      id: 'trigger-expanded',
      requirement: 'required',
      rule: 'While the menu is displayed, the button has aria-expanded set to true.',
      ...TRIGGER_EXPANDED,
    },
    {
      id: 'trigger-controls-menu',
      requirement: 'optional',
      rule: 'The button may have aria-controls referring to the menu.',
      target: { part: 'trigger' },
      attribute: 'aria-controls',
      references: 'menu',
    },
  ],
  keyboard: [
    {
      id: 'enter-opens',
      key: 'Enter',
      keys: '{Enter}',
      requirement: 'required',
      given: { open: false, focus: { part: 'trigger' } },
      result: 'Opens the menu and moves focus to the first item.',
      then: { open: true, focus: { part: 'item', at: 'first' }, attributes: [TRIGGER_EXPANDED] },
    },
    {
      id: 'space-opens',
      key: 'Space',
      keys: '{ }',
      requirement: 'required',
      given: { open: false, focus: { part: 'trigger' } },
      result: 'Opens the menu and moves focus to the first item.',
      then: { open: true, focus: { part: 'item', at: 'first' }, attributes: [TRIGGER_EXPANDED] },
    },
    {
      id: 'down-arrow-opens',
      key: 'Down Arrow',
      keys: '{ArrowDown}',
      requirement: 'optional',
      given: { open: false, focus: { part: 'trigger' } },
      result: 'Opens the menu and moves focus to the first item.',
      then: { open: true, focus: { part: 'item', at: 'first' } },
    },
    {
      id: 'up-arrow-opens-at-last',
      key: 'Up Arrow',
      keys: '{ArrowUp}',
      requirement: 'optional',
      given: { open: false, focus: { part: 'trigger' } },
      result: 'Opens the menu and moves focus to the last item.',
      then: { open: true, focus: { part: 'item', at: 'last' } },
    },
    {
      id: 'down-arrow-next',
      key: 'Down Arrow',
      keys: '{ArrowDown}',
      requirement: 'required',
      given: { open: true, focus: { part: 'item', at: 'first' } },
      result: 'Moves focus to the next item.',
      then: { open: true, focus: { part: 'item', at: 1 } },
    },
    {
      id: 'down-arrow-wraps',
      key: 'Down Arrow',
      keys: '{ArrowDown}',
      requirement: 'optional',
      when: { wrap: 'wrap' },
      given: { open: true, focus: { part: 'item', at: 'last' } },
      result: 'On the last item, moves focus to the first item.',
      then: { open: true, focus: { part: 'item', at: 'first' } },
    },
    {
      id: 'down-arrow-stops',
      key: 'Down Arrow',
      keys: '{ArrowDown}',
      requirement: 'optional',
      when: { wrap: 'stop' },
      given: { open: true, focus: { part: 'item', at: 'last' } },
      result: 'On the last item, focus stays on the last item.',
      then: { open: true, focus: { part: 'item', at: 'last' } },
    },
    {
      id: 'up-arrow-previous',
      key: 'Up Arrow',
      keys: '{ArrowUp}',
      requirement: 'required',
      given: { open: true, focus: { part: 'item', at: 1 } },
      result: 'Moves focus to the previous item.',
      then: { open: true, focus: { part: 'item', at: 'first' } },
    },
    {
      id: 'up-arrow-wraps',
      key: 'Up Arrow',
      keys: '{ArrowUp}',
      requirement: 'optional',
      when: { wrap: 'wrap' },
      given: { open: true, focus: { part: 'item', at: 'first' } },
      result: 'On the first item, moves focus to the last item.',
      then: { open: true, focus: { part: 'item', at: 'last' } },
    },
    {
      id: 'up-arrow-stops',
      key: 'Up Arrow',
      keys: '{ArrowUp}',
      requirement: 'optional',
      when: { wrap: 'stop' },
      given: { open: true, focus: { part: 'item', at: 'first' } },
      result: 'On the first item, focus stays on the first item.',
      then: { open: true, focus: { part: 'item', at: 'first' } },
    },
    {
      id: 'home-first',
      key: 'Home',
      keys: '{Home}',
      requirement: 'optional',
      given: { open: true, focus: { part: 'item', at: 'last' } },
      result: 'Moves focus to the first item.',
      then: { open: true, focus: { part: 'item', at: 'first' } },
    },
    {
      id: 'end-last',
      key: 'End',
      keys: '{End}',
      requirement: 'optional',
      given: { open: true, focus: { part: 'item', at: 'first' } },
      result: 'Moves focus to the last item.',
      then: { open: true, focus: { part: 'item', at: 'last' } },
    },
    {
      id: 'enter-activates',
      key: 'Enter',
      keys: '{Enter}',
      requirement: 'required',
      given: { open: true, focus: { part: 'item', at: 'first' } },
      result: 'Activates the item and closes the menu.',
      then: { open: false },
    },
    {
      id: 'escape-closes',
      key: 'Escape',
      keys: '{Escape}',
      requirement: 'required',
      given: { open: true, focus: { part: 'item', at: 'first' } },
      result: 'Closes the menu and returns focus to the button that opened it.',
      then: { open: false, focus: { part: 'trigger' }, attributes: [TRIGGER_COLLAPSED] },
    },
    {
      id: 'tab-closes',
      key: 'Tab',
      keys: '{Tab}',
      requirement: 'required',
      given: { open: true, focus: { part: 'item', at: 'first' } },
      result: 'Moves focus out of the menu and closes it.',
      then: { open: false },
    },
  ],
}
