// Generated by scripts/generate-a11y-ios-contracts.mjs from the APG pattern
// contracts in @atom63/ui-foundation (src/a11y). Do not edit; change the
// contract and run `pnpm --filter @atom63/ui-foundation generate:a11y-ios`.

import XCTest

extension A11yIOSContract {
  static let all: [A11yIOSContract] = [
  .init(
    pattern: "accordion",
    catalogItem: "disclosureGroup",
    parts: [
      "header": .init(type: .button, nameRequired: true, scope: .preview),
      "panel": .init(type: .staticText, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "header", at: nil, label: "Implementation details"), exists: nil, enabled: true, selected: nil, value: nil, labelIncludes: nil),
      .init(target: .init(part: "header", at: nil, label: "Unavailable details"), exists: nil, enabled: false, selected: nil, value: nil, labelIncludes: nil),
      .init(target: .init(part: "panel", at: nil, label: "Native SwiftUI renderer with shared product intent."), exists: false, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-expands",
        on: .init(part: "header", at: nil, label: "Implementation details"),
        given: [],
        then: [
          .init(target: .init(part: "panel", at: nil, label: "Native SwiftUI renderer with shared product intent."), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Expands the section and shows its content."
      ),
      .init(
        id: "activation-collapses",
        on: .init(part: "header", at: nil, label: "Implementation details"),
        given: [],
        then: [
          .init(target: .init(part: "panel", at: nil, label: "Native SwiftUI renderer with shared product intent."), exists: false, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Collapses the section and hides its content."
      ),
    ]
  ),
  .init(
    pattern: "alertdialog",
    catalogItem: "confirmationDialog",
    parts: [
      "alert": .init(type: .alert, nameRequired: true, scope: .app),
      "cancel": .init(type: .button, nameRequired: true, scope: .app),
      "trigger": .init(type: .button, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "trigger", at: .first, label: nil), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-opens-alert",
        on: .init(part: "trigger", at: .first, label: nil),
        given: [],
        then: [
          .init(target: .init(part: "alert", at: .first, label: nil), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Opens the alert dialog, named by its title."
      ),
      .init(
        id: "cancel-closes-alert",
        on: .init(part: "cancel", at: nil, label: "Cancel"),
        given: [],
        then: [
          .init(target: .init(part: "alert", at: nil, label: nil), exists: false, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Closes the alert without performing the action."
      ),
    ]
  ),
  .init(
    pattern: "combobox-select-only",
    catalogItem: "picker",
    parts: [
      "option": .init(type: .button, nameRequired: true, scope: .popup),
      "trigger": .init(type: .button, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "trigger", at: .first, label: nil), exists: nil, enabled: nil, selected: nil, value: nil, labelIncludes: "Draft"),
      .init(target: .init(part: "trigger", at: .last, label: nil), exists: nil, enabled: false, selected: nil, value: nil, labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-opens-options",
        on: .init(part: "trigger", at: .first, label: nil),
        given: [],
        then: [
          .init(target: .init(part: "option", at: nil, label: nil), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
          .init(target: .init(part: "option", at: nil, label: "Draft"), exists: nil, enabled: nil, selected: true, value: nil, labelIncludes: nil),
          .init(target: .init(part: "option", at: nil, label: "Active"), exists: nil, enabled: nil, selected: false, value: nil, labelIncludes: nil),
        ],
        result: "Opens the list of options with the current one selected."
      ),
      .init(
        id: "choosing-an-option-closes-and-updates",
        on: .init(part: "option", at: nil, label: "Active"),
        given: [],
        then: [
          .init(target: .init(part: "option", at: nil, label: nil), exists: false, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
          .init(target: .init(part: "trigger", at: .first, label: nil), exists: nil, enabled: nil, selected: nil, value: nil, labelIncludes: "Active"),
        ],
        result: "Selects the option, closes the list and shows the new value."
      ),
    ]
  ),
  .init(
    pattern: "dialog-modal",
    catalogItem: "sheet",
    parts: [
      "close": .init(type: .button, nameRequired: true, scope: .app),
      "title": .init(type: .staticText, nameRequired: true, scope: .app),
      "trigger": .init(type: .button, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "trigger", at: nil, label: "Open project sheet"), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-opens-sheet",
        on: .init(part: "trigger", at: nil, label: "Open project sheet"),
        given: [],
        then: [
          .init(target: .init(part: "title", at: nil, label: "Project details"), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
          .init(target: .init(part: "close", at: nil, label: "Done"), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Opens the sheet, named by its title, with a way to close it."
      ),
      .init(
        id: "close-dismisses-sheet",
        on: .init(part: "close", at: nil, label: "Done"),
        given: [],
        then: [
          .init(target: .init(part: "title", at: nil, label: "Project details"), exists: false, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
          .init(target: .init(part: "trigger", at: nil, label: "Open project sheet"), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Closes the sheet and returns to the view that opened it."
      ),
    ]
  ),
  .init(
    pattern: "menu-button",
    catalogItem: "menu",
    parts: [
      "item": .init(type: .button, nameRequired: true, scope: .popup),
      "trigger": .init(type: .button, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "trigger", at: .first, label: nil), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-opens-menu",
        on: .init(part: "trigger", at: .first, label: nil),
        given: [],
        then: [
          .init(target: .init(part: "item", at: nil, label: nil), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
          .init(target: .init(part: "item", at: nil, label: "Show details"), exists: nil, enabled: nil, selected: true, value: nil, labelIncludes: nil),
          .init(target: .init(part: "item", at: nil, label: "Unavailable action"), exists: nil, enabled: false, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Opens the menu."
      ),
      .init(
        id: "activating-an-item-closes-menu",
        on: .init(part: "item", at: nil, label: "Duplicate"),
        given: [],
        then: [
          .init(target: .init(part: "item", at: nil, label: nil), exists: false, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Performs the action and closes the menu."
      ),
    ]
  ),
  .init(
    pattern: "radio",
    catalogItem: "radioGroup",
    parts: [
      "group": .init(type: .staticText, nameRequired: true, scope: .preview),
      "option": .init(type: .button, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "group", at: nil, label: "Default project view"), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
      .init(target: .init(part: "option", at: nil, label: "Grid"), exists: nil, enabled: nil, selected: true, value: nil, labelIncludes: nil),
      .init(target: .init(part: "option", at: nil, label: "List"), exists: nil, enabled: nil, selected: false, value: nil, labelIncludes: nil),
      .init(target: .init(part: "option", at: nil, label: "Timeline"), exists: nil, enabled: false, selected: nil, value: nil, labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-selects-option",
        on: .init(part: "option", at: nil, label: "List"),
        given: [],
        then: [
          .init(target: .init(part: "option", at: nil, label: "List"), exists: nil, enabled: nil, selected: true, value: nil, labelIncludes: nil),
          .init(target: .init(part: "option", at: nil, label: "Grid"), exists: nil, enabled: nil, selected: false, value: nil, labelIncludes: nil),
        ],
        result: "Selects the option and clears the previous selection."
      ),
    ]
  ),
  .init(
    pattern: "switch",
    catalogItem: "toggle",
    parts: [
      "switch": .init(type: .switch, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "switch", at: .first, label: nil), exists: nil, enabled: nil, selected: nil, value: "1", labelIncludes: nil),
      .init(target: .init(part: "switch", at: .last, label: nil), exists: nil, enabled: nil, selected: nil, value: "0", labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-turns-off",
        on: .init(part: "switch", at: .first, label: nil),
        given: [],
        then: [
          .init(target: .init(part: "switch", at: .first, label: nil), exists: nil, enabled: nil, selected: nil, value: "0", labelIncludes: nil),
        ],
        result: "Changes the state of the switch."
      ),
      .init(
        id: "activation-turns-on",
        on: .init(part: "switch", at: .first, label: nil),
        given: [],
        then: [
          .init(target: .init(part: "switch", at: .first, label: nil), exists: nil, enabled: nil, selected: nil, value: "1", labelIncludes: nil),
        ],
        result: "Changes the state of the switch back."
      ),
    ]
  ),
  .init(
    pattern: "tabs",
    catalogItem: "tabs",
    parts: [
      "panel": .init(type: .staticText, nameRequired: true, scope: .preview),
      "tab": .init(type: .button, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "tab", at: nil, label: "Overview"), exists: nil, enabled: nil, selected: true, value: nil, labelIncludes: nil),
      .init(target: .init(part: "tab", at: nil, label: "Activity"), exists: nil, enabled: nil, selected: false, value: nil, labelIncludes: nil),
      .init(target: .init(part: "panel", at: nil, label: "Project summary and current status."), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-selects-tab",
        on: .init(part: "tab", at: nil, label: "Activity"),
        given: [],
        then: [
          .init(target: .init(part: "tab", at: nil, label: "Activity"), exists: nil, enabled: nil, selected: true, value: nil, labelIncludes: nil),
          .init(target: .init(part: "tab", at: nil, label: "Overview"), exists: nil, enabled: nil, selected: false, value: nil, labelIncludes: nil),
          .init(target: .init(part: "panel", at: nil, label: "Recent project changes."), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
          .init(target: .init(part: "panel", at: nil, label: "Project summary and current status."), exists: false, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Selects the tab and shows its content in place of the previous one."
      ),
    ]
  ),
  ]
}
