// Generated by scripts/generate-a11y-ios-contracts.mjs from the APG pattern
// contracts in @atom63/ui-foundation (src/a11y). Do not edit; change the
// contract and run `pnpm --filter @atom63/ui-foundation generate:a11y-ios`.

import XCTest

extension A11yIOSContract {
  static let all: [A11yIOSContract] = [
  .init(
    pattern: "alertdialog",
    catalogItem: "confirmationDialog",
    parts: [
      "alert": .init(type: .alert, nameRequired: true, scope: .app),
      "cancel": .init(type: .button, nameRequired: true, scope: .app),
      "trigger": .init(type: .button, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "trigger", at: .first, label: nil), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-opens-alert",
        on: .init(part: "trigger", at: .first, label: nil),
        given: [],
        then: [
          .init(target: .init(part: "alert", at: .first, label: nil), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Opens the alert dialog, named by its title."
      ),
      .init(
        id: "cancel-closes-alert",
        on: .init(part: "cancel", at: nil, label: "Cancel"),
        given: [],
        then: [
          .init(target: .init(part: "alert", at: nil, label: nil), exists: false, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Closes the alert without performing the action."
      ),
    ]
  ),
  .init(
    pattern: "combobox-select-only",
    catalogItem: "picker",
    parts: [
      "option": .init(type: .button, nameRequired: true, scope: .popup),
      "trigger": .init(type: .button, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "trigger", at: .first, label: nil), exists: nil, enabled: nil, selected: nil, value: nil, labelIncludes: "Draft"),
      .init(target: .init(part: "trigger", at: .last, label: nil), exists: nil, enabled: false, selected: nil, value: nil, labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-opens-options",
        on: .init(part: "trigger", at: .first, label: nil),
        given: [],
        then: [
          .init(target: .init(part: "option", at: nil, label: nil), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
          .init(target: .init(part: "option", at: nil, label: "Draft"), exists: nil, enabled: nil, selected: true, value: nil, labelIncludes: nil),
          .init(target: .init(part: "option", at: nil, label: "Active"), exists: nil, enabled: nil, selected: false, value: nil, labelIncludes: nil),
        ],
        result: "Opens the list of options with the current one selected."
      ),
      .init(
        id: "choosing-an-option-closes-and-updates",
        on: .init(part: "option", at: nil, label: "Active"),
        given: [],
        then: [
          .init(target: .init(part: "option", at: nil, label: nil), exists: false, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
          .init(target: .init(part: "trigger", at: .first, label: nil), exists: nil, enabled: nil, selected: nil, value: nil, labelIncludes: "Active"),
        ],
        result: "Selects the option, closes the list and shows the new value."
      ),
    ]
  ),
  .init(
    pattern: "menu-button",
    catalogItem: "menu",
    parts: [
      "item": .init(type: .button, nameRequired: true, scope: .popup),
      "trigger": .init(type: .button, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "trigger", at: .first, label: nil), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-opens-menu",
        on: .init(part: "trigger", at: .first, label: nil),
        given: [],
        then: [
          .init(target: .init(part: "item", at: nil, label: nil), exists: true, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
          .init(target: .init(part: "item", at: nil, label: "Show details"), exists: nil, enabled: nil, selected: true, value: nil, labelIncludes: nil),
          .init(target: .init(part: "item", at: nil, label: "Unavailable action"), exists: nil, enabled: false, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Opens the menu."
      ),
      .init(
        id: "activating-an-item-closes-menu",
        on: .init(part: "item", at: nil, label: "Duplicate"),
        given: [],
        then: [
          .init(target: .init(part: "item", at: nil, label: nil), exists: false, enabled: nil, selected: nil, value: nil, labelIncludes: nil),
        ],
        result: "Performs the action and closes the menu."
      ),
    ]
  ),
  .init(
    pattern: "switch",
    catalogItem: "toggle",
    parts: [
      "switch": .init(type: .switch, nameRequired: true, scope: .preview),
    ],
    structure: [
      .init(target: .init(part: "switch", at: .first, label: nil), exists: nil, enabled: nil, selected: nil, value: "1", labelIncludes: nil),
      .init(target: .init(part: "switch", at: .last, label: nil), exists: nil, enabled: nil, selected: nil, value: "0", labelIncludes: nil),
    ],
    interactions: [
      .init(
        id: "activation-turns-off",
        on: .init(part: "switch", at: .first, label: nil),
        given: [],
        then: [
          .init(target: .init(part: "switch", at: .first, label: nil), exists: nil, enabled: nil, selected: nil, value: "0", labelIncludes: nil),
        ],
        result: "Changes the state of the switch."
      ),
      .init(
        id: "activation-turns-on",
        on: .init(part: "switch", at: .first, label: nil),
        given: [],
        then: [
          .init(target: .init(part: "switch", at: .first, label: nil), exists: nil, enabled: nil, selected: nil, value: "1", labelIncludes: nil),
        ],
        result: "Changes the state of the switch back."
      ),
    ]
  ),
  ]
}
