// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  paginationContract,
  paginationSlots,
  paginationStates,
  paginationVisualArchetypes,
} from './pagination-contract'
export type {
  PaginationContract,
  PaginationSlot,
  PaginationState,
  PaginationVisualArchetype,
} from './pagination-contract'
