// Generated by scripts/generate-component-contracts.mjs from packages/ui-foundation/contracts/components/pagination.json.
// Do not edit; change the JSON and run `pnpm --filter @atom63/ui-foundation generate:contracts`.

import type { VisualArchetypeId } from '../../visual-archetypes'
import { type ButtonSize, buttonSizes } from '../button/button-contract'

export const paginationStates = ['rest', 'current'] as const
export const paginationSlots = [
  'pagination',
  'pagination-content',
  'pagination-item',
  'pagination-link',
  'pagination-ellipsis',
] as const
export const paginationVisualArchetypes = ['action'] as const satisfies readonly VisualArchetypeId[]

export type PaginationState = (typeof paginationStates)[number]
export type PaginationSlot = (typeof paginationSlots)[number]
export type PaginationVisualArchetype = (typeof paginationVisualArchetypes)[number]

export interface PaginationContract {
  defaultLinkSize: ButtonSize
  linkSizes: readonly ButtonSize[]
  slots: readonly PaginationSlot[]
  states: readonly PaginationState[]
  visualArchetypes: readonly PaginationVisualArchetype[]
}

export const paginationContract = {
  defaultLinkSize: 'icon',
  linkSizes: buttonSizes,
  slots: paginationSlots,
  states: paginationStates,
  visualArchetypes: paginationVisualArchetypes,
} satisfies PaginationContract
