import { readFileSync, writeFileSync } from 'node:fs'

// The minified runtime, as a string constant scripts.ts inlines into use_figma scripts.
const source = readFileSync(new URL('../dist/runtime/runtime.global.js', import.meta.url), 'utf8')
writeFileSync(
  new URL('../src/runtime-source.generated.ts', import.meta.url),
  `// Generated by scripts/embed-runtime.mjs from src/runtime.ts. Do not edit.\n` +
    `export const RUNTIME_SOURCE = ${JSON.stringify(source.replace(/\n\/\/# sourceMappingURL=.*$/, '').trim())}\n`
)
