import { readFileSync, writeFileSync } from 'node:fs'

// The minified runtimes, as string constants the script builders inline into use_figma scripts:
// the token runtime (scripts.ts) and the component runtime (components/scripts.ts).
const read = name =>
  JSON.stringify(
    readFileSync(new URL(`../dist/runtime/${name}.global.js`, import.meta.url), 'utf8')
      .replace(/\n\/\/# sourceMappingURL=.*$/, '')
      .trim()
  )
writeFileSync(
  new URL('../src/runtime-source.generated.ts', import.meta.url),
  `// Generated by scripts/embed-runtime.mjs from src/runtime.ts and src/runtime-components.ts. Do not edit.\n` +
    `export const RUNTIME_SOURCE = ${read('runtime')}\n` +
    `export const COMPONENT_RUNTIME_SOURCE = ${read('runtime-components')}\n`
)
