import { describe, expect, it } from 'vitest'
import routerSource from './router.tsx?raw'
import routeTreeSource from './routeTree.gen.ts?raw'

describe('router baseline', () => {
  it('registers TanStack Router with the generated route tree', () => {
    expect(routerSource).toContain('createRouter')
    expect(routerSource).toContain('routeTree')
    expect(routerSource).toContain("declare module '@tanstack/react-router'")
  })

  it('commits the generated route tree artifact', () => {
    expect(routeTreeSource).toContain('This file was automatically generated by TanStack Router.')
  })
})
