/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreaRouteImport } from './routes/$area'
import { Route as AreaSlugRouteImport } from './routes/$area/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRoute = AreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaSlugRoute = AreaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AreaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$area': typeof AreaRouteWithChildren
  '/$area/$slug': typeof AreaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$area': typeof AreaRouteWithChildren
  '/$area/$slug': typeof AreaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$area': typeof AreaRouteWithChildren
  '/$area/$slug': typeof AreaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$area' | '/$area/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$area' | '/$area/$slug'
  id: '__root__' | '/' | '/$area' | '/$area/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaRoute: typeof AreaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$area': {
      id: '/$area'
      path: '/$area'
      fullPath: '/$area'
      preLoaderRoute: typeof AreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$area/$slug': {
      id: '/$area/$slug'
      path: '/$slug'
      fullPath: '/$area/$slug'
      preLoaderRoute: typeof AreaSlugRouteImport
      parentRoute: typeof AreaRoute
    }
  }
}

interface AreaRouteChildren {
  AreaSlugRoute: typeof AreaSlugRoute
}

const AreaRouteChildren: AreaRouteChildren = {
  AreaSlugRoute: AreaSlugRoute,
}

const AreaRouteWithChildren = AreaRoute._addFileChildren(AreaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaRoute: AreaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
