// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  commandContract,
  commandSlots,
  commandStates,
  commandVisualArchetypes,
} from './command-contract'
export type {
  CommandContract,
  CommandSlot,
  CommandState,
  CommandVisualArchetype,
} from './command-contract'
