// Generated by scripts/generate-component-contracts.mjs from packages/ui-foundation/contracts/components/radio.json.
// Do not edit; change the JSON and run `pnpm --filter @atom63/ui-foundation generate:contracts`.

import type { A11yPatternBinding } from '../../a11y/types'
import type { VisualArchetypeId } from '../../visual-archetypes'

export const radioSizes = ['sm', 'md'] as const
export const radioStates = ['unchecked', 'checked', 'focus-visible', 'disabled', 'invalid'] as const
export const radioSlots = ['radio-group', 'radio', 'radio-indicator'] as const
export const radioVisualArchetypes = ['choice'] as const satisfies readonly VisualArchetypeId[]

export type RadioSize = (typeof radioSizes)[number]
export type RadioState = (typeof radioStates)[number]
export type RadioSlot = (typeof radioSlots)[number]
export type RadioVisualArchetype = (typeof radioVisualArchetypes)[number]

export interface RadioContract {
  /** The WAI-ARIA APG pattern the component implements. */
  accessibility: A11yPatternBinding
  defaultSize: RadioSize
  sizes: readonly RadioSize[]
  states: readonly RadioState[]
  slots: readonly RadioSlot[]
  visualArchetypes: readonly RadioVisualArchetype[]
}

export const radioContract = {
  accessibility: { pattern: 'radio' },
  defaultSize: 'md',
  sizes: radioSizes,
  states: radioStates,
  slots: radioSlots,
  visualArchetypes: radioVisualArchetypes,
} satisfies RadioContract
