// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  accordionContract,
  accordionIconVariants,
  accordionSlots,
  accordionStates,
  accordionVisualArchetypes,
} from './accordion-contract'
export type {
  AccordionContract,
  AccordionIconVariant,
  AccordionSlot,
  AccordionState,
  AccordionVisualArchetype,
} from './accordion-contract'
