// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  skeletonContract,
  skeletonSlots,
  skeletonStates,
  skeletonVisualArchetypes,
} from './skeleton-contract'
export type {
  SkeletonContract,
  SkeletonSlot,
  SkeletonState,
  SkeletonVisualArchetype,
} from './skeleton-contract'
