// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  tableContract,
  tableSlots,
  tableStates,
  tableVariants,
  tableVisualArchetypes,
} from './table-contract'
export type {
  TableContract,
  TableSlot,
  TableState,
  TableVariant,
  TableVisualArchetype,
} from './table-contract'
