// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export { kbdContract, kbdSizes, kbdSlots, kbdStates, kbdVisualArchetypes } from './kbd-contract'
export type { KbdContract, KbdSize, KbdSlot, KbdState, KbdVisualArchetype } from './kbd-contract'
