// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  textTickerContract,
  textTickerSlots,
  textTickerStates,
  textTickerVariants,
  textTickerVisualArchetypes,
} from './text-ticker-contract'
export type {
  TextTickerContract,
  TextTickerSlot,
  TextTickerState,
  TextTickerVariant,
  TextTickerVisualArchetype,
} from './text-ticker-contract'
