// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  avatarCompositions,
  avatarContract,
  avatarSizes,
  avatarSlots,
  avatarStates,
  avatarVisualArchetypes,
} from './avatar-contract'
export type {
  AvatarComposition,
  AvatarContract,
  AvatarSize,
  AvatarSlot,
  AvatarState,
  AvatarVisualArchetype,
} from './avatar-contract'
