// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  frameBorders,
  frameContract,
  framePanelSurfaces,
  framePresets,
  frameSlots,
  frameStates,
  frameTrays,
  frameVariants,
  frameVisualArchetypes,
} from './frame-contract'
export type {
  FrameBorder,
  FrameContract,
  FramePanelSurface,
  FrameSlot,
  FrameState,
  FrameTray,
  FrameVariant,
  FrameVisualArchetype,
} from './frame-contract'
export * from './frame-chrome'
