// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  separatorContract,
  separatorModes,
  separatorOrientations,
  separatorSlots,
  separatorVariants,
  separatorVisualArchetypes,
} from './separator-contract'
export type {
  SeparatorContract,
  SeparatorMode,
  SeparatorOrientation,
  SeparatorSlot,
  SeparatorVariant,
  SeparatorVisualArchetype,
} from './separator-contract'
