// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  marqueeContract,
  marqueeOrientations,
  marqueeSlots,
  marqueeStates,
  marqueeVisualArchetypes,
} from './marquee-contract'
export type {
  MarqueeContract,
  MarqueeOrientation,
  MarqueeSlot,
  MarqueeState,
} from './marquee-contract'
