// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  switchContract,
  switchSizes,
  switchSlots,
  switchStates,
  switchVisualArchetypes,
} from './switch-contract'
export type {
  SwitchContract,
  SwitchSize,
  SwitchSlot,
  SwitchState,
  SwitchVisualArchetype,
} from './switch-contract'
