// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export { labelContract, labelSlots, labelStates, labelVisualArchetypes } from './label-contract'
export type { LabelContract, LabelSlot, LabelState, LabelVisualArchetype } from './label-contract'
