// Generated by scripts/generate-inform-vectors.mjs from the web arbiter in
// @atom63/inform. Do not edit; change the cases there and run
// `node scripts/generate-inform-vectors.mjs`.

import Foundation

let informVectorNow = vectorDate("2026-09-28T12:00:00.000Z")

let informVectors: [InformVector] = [
  InformVector(
    name: "ranks by priority, declaration order breaking ties",
    messages: [
      .init(id: "low", surface: .banner, priority: 1, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
      .init(id: "high-first", surface: .banner, priority: 5, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
      .init(id: "high-second", surface: .banner, priority: 5, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
    ],
    dismissals: [],
    anchors: [],
    banner: "high-first",
    dialog: nil,
    spotlight: nil,
    flyouts: []
  ),
  InformVector(
    name: "skips dismissed messages by id and version",
    messages: [
      .init(id: "seen", surface: .banner, priority: 9, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
      .init(id: "bumped", surface: .banner, priority: 5, dismiss: .persistent, version: 2, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
      .init(id: "fallback", surface: .banner, priority: 1, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
    ],
    dismissals: ["seen:1","bumped:1"],
    anchors: [],
    banner: "bumped",
    dialog: nil,
    spotlight: nil,
    flyouts: []
  ),
  InformVector(
    name: "respects start and end times",
    messages: [
      .init(id: "not-yet", surface: .banner, priority: 9, dismiss: .persistent, version: 1, startsAt: vectorDate("2026-09-28T12:00:01.000Z"), endsAt: nil, anchor: nil, eligible: true),
      .init(id: "over", surface: .banner, priority: 8, dismiss: .persistent, version: 1, startsAt: nil, endsAt: vectorDate("2026-09-28T11:59:59.000Z"), anchor: nil, eligible: true),
      .init(id: "live", surface: .banner, priority: 1, dismiss: .persistent, version: 1, startsAt: vectorDate("2026-09-28T12:00:00.000Z"), endsAt: vectorDate("2026-09-28T12:00:00.000Z"), anchor: nil, eligible: true),
    ],
    dismissals: [],
    anchors: [],
    banner: "live",
    dialog: nil,
    spotlight: nil,
    flyouts: []
  ),
  InformVector(
    name: "skips messages whose predicate is false",
    messages: [
      .init(id: "hidden", surface: .dialog, priority: 9, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: false),
      .init(id: "shown", surface: .dialog, priority: 0, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
    ],
    dismissals: [],
    anchors: [],
    banner: nil,
    dialog: "shown",
    spotlight: nil,
    flyouts: []
  ),
  InformVector(
    name: "skips a spotlight whose anchor is missing",
    messages: [
      .init(id: "lost", surface: .spotlight, priority: 9, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: "gone", eligible: true),
      .init(id: "found", surface: .spotlight, priority: 0, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: "here", eligible: true),
    ],
    dismissals: [],
    anchors: ["here"],
    banner: nil,
    dialog: nil,
    spotlight: "found",
    flyouts: []
  ),
  InformVector(
    name: "a dialog blocks the spotlight and the flyouts, not the banner",
    messages: [
      .init(id: "dialog", surface: .dialog, priority: 0, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
      .init(id: "spot", surface: .spotlight, priority: 9, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: "here", eligible: true),
      .init(id: "flyout", surface: .cornerFlyout, priority: 0, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
      .init(id: "banner", surface: .banner, priority: 0, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
    ],
    dismissals: [],
    anchors: ["here"],
    banner: "banner",
    dialog: "dialog",
    spotlight: nil,
    flyouts: []
  ),
  InformVector(
    name: "a spotlight blocks the flyouts when no dialog is eligible",
    messages: [
      .init(id: "spot", surface: .spotlight, priority: 0, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: "here", eligible: true),
      .init(id: "flyout", surface: .cornerFlyout, priority: 0, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
    ],
    dismissals: [],
    anchors: ["here"],
    banner: nil,
    dialog: nil,
    spotlight: "spot",
    flyouts: []
  ),
  InformVector(
    name: "stacks at most three flyouts",
    messages: [
      .init(id: "f1", surface: .cornerFlyout, priority: 1, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
      .init(id: "f2", surface: .cornerFlyout, priority: 4, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
      .init(id: "f3", surface: .cornerFlyout, priority: 3, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
      .init(id: "f4", surface: .cornerFlyout, priority: 2, dismiss: .persistent, version: 1, startsAt: nil, endsAt: nil, anchor: nil, eligible: true),
    ],
    dismissals: [],
    anchors: [],
    banner: nil,
    dialog: nil,
    spotlight: nil,
    flyouts: ["f2","f3","f4"]
  ),
  InformVector(
    name: "resolves nothing from an empty registry",
    messages: [],
    dismissals: [],
    anchors: [],
    banner: nil,
    dialog: nil,
    spotlight: nil,
    flyouts: []
  ),
]
