// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  badgeContract,
  badgePaletteVariants,
  badgeSemanticVariants,
  badgeSizes,
  badgeSlots,
  badgeSolidVariants,
  badgeStates,
  badgeVariants,
  badgeVisualArchetypes,
} from './badge-contract'
export type {
  BadgeContract,
  BadgeSize,
  BadgeSlot,
  BadgeState,
  BadgeVariant,
  BadgeVisualArchetype,
} from './badge-contract'
