// Generated by scripts/generate-component-contracts.mjs. Do not edit.
export {
  collapsibleContract,
  collapsibleSlots,
  collapsibleStates,
  collapsibleVisualArchetypes,
} from './collapsible-contract'
export type {
  CollapsibleContract,
  CollapsibleSlot,
  CollapsibleState,
  CollapsibleVisualArchetype,
} from './collapsible-contract'
